# define programming language
language: go

# specify which go version should be tested against project
go:
  - "1.15.x"
  - "1.14.x"
  - tip

env:
  - GO111MODULE=off

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

notifications:
  email: false

before_script:
  # all .go files, excluding vendor/
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  # install linter
  - go get golang.org/x/lint/golint
  # install static analyzer/linter
  - go get honnef.co/go/tools/cmd/staticcheck
  # install gocyclo
  - go get github.com/fzipp/gocyclo
  # install dependencies
  - make vendor

script:
  # run all tests
  - go test -race -coverprofile=coverage.out -covermode=atomic ./...
  # run go vet
  - go vet ./...
  # "go vet on steroids" + linter
  - staticcheck ./...
  # forbid code with huge functions
  - gocyclo -over 19 $GO_FILES
  # linter
  - golint -set_exit_status $(go list ./...)

after_success:
  - bash <(curl -s https://codecov.io/bash)